apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base2/speedtest
namePrefix: prod-
# not really needed, since the original files should (?) be the prod version
# patches:
#   - path: ./change_speedtest_domain.yaml
#   - path: ./change_speedtest_service_selector.yaml
#   - path: ./change_speedtest_pod_label.yaml
