apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: prod
resources:
  - ../../workloads/speedtest/
namePrefix: prod-
# not really needed, since the original files should (?) be the prod version
patches:
  # ollama patches
  # - path: ./ollama_add_gpu.yaml
