apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "radarr-outgoing"
spec:
  endpointSelector:
    matchLabels:
      app: radarr
  egress:
    - toEntities:
        - world
    - toPorts:
        - ports:
            # - port: "53"
            #   protocol: ANY
            - port: "443"
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "radarr-api-access"
spec:
  endpointSelector:
    matchLabels:
      app: radarr
  ingress:
    - fromEndpoints:
        - matchLabels:
            radarr: "allow"
    - toPorts:
        - ports:
            - port: "7878"
              protocol: TCP
