apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "radarr"
spec:
  endpointSelector:
    matchLabels:
      app: radarr
  egress:
    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - fromEndpoints:
        - matchLabels:
            radarr: "allow"
      toPorts:
        - ports:
            - port: "7878"
              protocol: TCP
