apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: radarr
spec:
  endpointSelector:
    matchLabels:
      app: radarr
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "7878"
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                app: prowlarr
    - toServices:
        - k8sServiceSelector:
            selector:
              matchLabels:
                app: qbittorrent
