apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyseerr"
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  egress:
    - toEndpoints:
        - matchLabels:
            app: sonarr
          toPorts:
            - ports:
                - port: "8989"
                  protocol: TCP

    - toEndpoints:
        - matchLabels:
            app: radarr
          toPorts:
            - ports:
                - port: "7878"
                  protocol: TCP

    - toEndpoints:
        - matchLabels:
            app: jellyfin
          toPorts:
            - ports:
                - port: "8096"
                  protocol: TCP

    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY

    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "5055"
              protocol: TCP
    # - fromEndpoints:
    #     - matchLabels:
    #         name: "cilium-envoy"
    #   toPorts:
    #     - ports:
    #         - port: "5055"
    #           protocol: TCP
