apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyseerr-outgoing"
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  egress:
    - toEntities:
        - world
    - toPorts:
        - ports:
            - port: "443"
              protocol: TCP
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyseerr-cluster"
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  egress:
    - toEntities:
        - cluster
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyseerr-webui-access"
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  ingress:
    - fromEndpoints:
        - matchLabels:
            name: "cilium-envoy"
    - toPorts:
        - ports:
            - port: "5055"
              protocol: TCP
