apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: jellyseerr
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  ingress:
    - fromCIDRSet:
        - cidr: "192.168.3.0/24"
  egress:
    - toEndpoints:
        - matchLabels:
            app: jellyfin
      toPorts:
        - ports:
            - port: "8096"
    - toEndpoints:
        - matchLabels:
            app: radarr
      toPorts:
        - ports:
            - port: "7878"
    - toEndpoints:
        - matchLabels:
            app: sonarr
      toPorts:
        - ports:
            - port: "8989"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toFQDNs:
        - matchName: image.tmdb.org
      toPorts:
        - ports:
            - port: "443"
    - toFQDNs:
        - matchName: www.omdbapi.com
      toPorts:
        - ports:
            - port: "443"
    - toFQDNs:
        - matchName: api.opensubtitles.com
      toPorts:
        - ports:
            - port: "443"
    - toFQDNs:
        - matchName: api.themoviedb.org
      toPorts:
        - ports:
            - port: "443"
