apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyseerr"
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  egress:
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "5055"
              protocol: TCP
