apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyseerr"
spec:
  endpointSelector:
    matchLabels:
      app: jellyseerr
  egress:
    - toEndpoints:
        - matchLabels:
            app: sonarr
    - toEndpoints:
        - matchLabels:
            app: radarr
    - toEndpoints:
        - matchLabels:
            app: jellyfin
    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "5055"
              protocol: TCP
    # - fromEndpoints:
    #     - matchLabels:
    #         name: "cilium-envoy"
    #   toPorts:
    #     - ports:
    #         - port: "5055"
    #           protocol: TCP
