apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "mkdocs only allow incomming tcp traffic on port 8000"
spec:
  endpointSelector:
    matchLabels:
      app: mkdocs
  egress:
    - toPorts:
        - ports:
  ingress:
    - toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
          # rules:
          #   http:
          #     - method: "GET"
          #       path: "/"
