apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speedtest-tls
spec:
  rules:
    - host: staging.speed.nilsherzig.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: speedtest-service
                port:
                  number: 80
  tls:
    - hosts:
        - staging.speed.nilsherzig.com
      secretName: staging-tls-speed-cert
