apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# namespace: staging
resources:
  - ../../workloads/speedtest/
  # - ../../workloads/ollama/
  # - ../../workloads/stremio/
  # - ../../workloads/argo/
  # - ../../workloads/open-webui/
  # - ../../workloads/llocalsearch/
namePrefix: staging-
patches:
  # speedtest patches
  - path: ./speedtest_change_domain.yaml
# argo cd patches
# - path: ./change_argo_ingress_domain.yaml
# - path: ./ollama_add_gpu.yaml
