apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../workloads/speedtest/
  - ../../workloads/fileshare/
namePrefix: staging-
patches:
  - path: ./speedtest_change_domain.yaml
