apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun # Optionally you can use the "qmcgaw/gluetun" image as well as specify what version of Gluetun you desire
          imagePullPolicy: Always

          securityContext:
            capabilities:
              add: ["NET_ADMIN"]

          readinessProbe:
            exec:
              command: ["/gluetun-entrypoint", "healthcheck"]
            initialDelaySeconds: 30
            periodSeconds: 5

          ports:
            - containerPort: 8888

          env:
            - name: HTTPPROXY
              value: "on"

            - name: HTTPPROXY_USER
              value: "test"

            - name: HTTPPROXY_PASSWORD
              value: "test"

            - name: HTTPPROXY_LOG
              value: "on"

            - name: TZ
              value: "Europe/Berlin"

            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"

            - name: VPN_TYPE
              value: "wireguard"

            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: wireguard-private-key
                  key: privatekey

                  # generate using the following kubectl command
                  # kubeclt create secret generic wireguard-private-key --from-literal=privatekey=[key]

            - name: WIREGUARD_ADDRESSES
              value: "10.71.170.87/32"

            - name: SERVER_CITIES
              value: "Copenhagen"

      volumes:
        - name: wireguard-private-key
          secret:
            secretName: wireguard-private-key
