apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  labels:
    app: gluetun
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      sidecarContainers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun # Optionally you can use the "qmcgaw/gluetun" image as well as specify what version of Gluetun you desire
          restartPolicy: Always
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          readinessProbe:
            exec:
              command: ["/gluetun-entrypoint", "healthcheck"]
            initialDelaySeconds: 30
            periodSeconds: 5
          env:
            - name: TZ
              value: "Europe/Berlin"

            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"

            - name: VPN_TYPE
              value: "wireguard"

            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: wireguard-private-key
                  key: privatekey
            # generate using the following kubectl command
            # kubeclt create secret generic wireguard-private-key --from-literal=privatekey=[key]

            - name: WIREGUARD_ADDRESSES
              value: "10.71.170.87/32"

            - name: SERVER_CITIES
              value: "Copenhagen"

            - name: FIREWALL_DEBUG
              value: "on"

      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          ports:
            - containerPort: 8080
            - containerPort: 6881
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: WEBUI_PORT
              value: "8080"
            - name: TORRENTING_PORT
              value: "6881"
          volumeMounts:
            - name: nfs-media
              mountPath: /downloads
              subPath: downloads/
            - name: nfs-configs
              mountPath: /config
              subPath: qbittorrent/
          resources:
            limits:
              memory: "2000Mi"
              cpu: "2000m"
            requests:
              memory: "500Mi"
              cpu: "500m"

      volumes:
        - name: wireguard-private-key
          secret:
            secretName: wireguard-private-key

        - name: nfs-media
          nfs:
            server: 10.10.10.146
            path: /mnt/bigdata/kubernetes/media/data
            readOnly: false
        - name: nfs-configs
          nfs:
            server: 10.10.10.146
            path: /mnt/bigdata/kubernetes/media/configs
            readOnly: false
