apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun-deployment
  labels:
    app: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: curl-container
          image: curlimages/curl
          command:
            [
              "sh",
              "-c",
              "while true; do curl -s -x socks5://test:test@localhost:1080 https://am.i.mullvad.net/connected; sleep 5; done",
            ]

        - name: socks5
          image: serjs/go-socks5-proxy
          ports:
            - containerPort: 1080
          env:
            - name: PROXY_USER
              value: "test"
            - name: PROXY_PASSWORD
              value: "test"

      initContainers:
        - name: gluetun
          image: ghcr.io/qdm12/gluetun # Optionally you can use the "qmcgaw/gluetun" image as well as specify what version of Gluetun you desire
          imagePullPolicy: Always
          restartPolicy: Always

          securityContext:
            capabilities:
              add: ["NET_ADMIN"]

          readinessProbe:
            exec:
              command: ["/gluetun-entrypoint", "healthcheck"]
            initialDelaySeconds: 30
            periodSeconds: 5

          env:
            - name: FIREWALL_INPUT_PORTS
              value: "8888"

            - name: TZ
              value: "Europe/Berlin"

            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"

            - name: VPN_TYPE
              value: "wireguard"

            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: wireguard-private-key
                  key: privatekey

                  # generate using the following kubectl command
                  # kubeclt create secret generic wireguard-private-key --from-literal=privatekey=[key]

            - name: WIREGUARD_ADDRESSES
              value: "10.71.170.87/32"

            - name: SERVER_CITIES
              value: "Copenhagen"

      volumes:
        - name: wireguard-private-key
          secret:
            secretName: wireguard-private-key
