apiVersion: v1
kind: Service
metadata:
  name: gluetun
spec:
  selector:
    app: gluetun
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
    - protocol: UDP
      port: 1080
      targetPort: 1080
