apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:latest
          env:
            - name: OLLAMA_BASE_URL
              value: "http://10.10.10.200:11434"
          ports:
            - containerPort: 3000
