apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fileshare"
spec:
  endpointSelector:
    matchLabels:
      app: fileshare
  egress:
    - toPorts:
        - ports:
  ingress:
    - toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
