apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileshare-deployment
  labels:
    app: fileshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileshare
  template:
    metadata:
      labels:
        app: fileshare
    spec:
      containers:
        - name: fileshare
          image: stonith404/pingvin-share
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - name: fileshare-data
              mountPath: /opt/app/backend/data
              subPath: data
      volumes:
        - name: fileshare-data
          persistentVolumeClaim:
            claimName: fileshare-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
---

