apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileshare-deployment
  labels:
    app: fileshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileshare
  template:
    metadata:
      labels:
        app: fileshare
    spec:
      containers:
        - name: fileshare
          image: stonith404/pingvin-share
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            # - name: fileshare-configs
            #   mountPath: /opt/app/backend/data/pingvin-share.db
            #   subPath: data/pingvin-share.db
            - name: fileshare-configs
              mountPath: /opt/app/backend/data/test.db
              subPath: test.db
            - name: fileshare-uploads
              mountPath: /opt/app/backend/data/uploads
              subPath: data/uploads/
      volumes:
        - name: fileshare-configs
          nfs:
            server: truenas
            path: /mnt/fast/fileshare-config/
            readOnly: false
        - name: fileshare-uploads
          nfs:
            server: truenas
            path: /mnt/bigdata/fileshare-uploads/
            readOnly: false
