apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileshare-deployment
  labels:
    app: fileshare
spec:
  replicas: 0
  selector:
    matchLabels:
      app: fileshare
  template:
    metadata:
      labels:
        app: fileshare
    spec:
      containers:
        - name: fileshare
          image: stonith404/pingvin-share
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - name: fileshare-configs
              mountPath: /opt/app/backend/data/pingvin-share.db
              subPath: data/pingvin-share.db
            - name: fileshare-uploads
              mountPath: /opt/app/backend/data/uploads
              subPath: uploads
      volumes:
        - name: fileshare-configs
          persistentVolumeClaim:
            claimName: fileshare-configs
        - name: fileshare-uploads
          persistentVolumeClaim:
            claimName: fileshare-uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare-configs
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare-uploads
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
