apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "fileshare"
spec:
  endpointSelector:
    matchLabels:
      app: fileshare
  egress:
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchName: "github.com"

        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
