---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: cloudflare@nilsherzig.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@nilsherzig.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
# im kinda confused on this one atm, but i think it would be nice to use a wildcard cert TODO
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-crt
#   namespace: cert-manager
# spec:
#   secretName: tls-secret
#   issuerRef:
#     kind: ClusterIssuer
#     name: letsencrypt-prod
#   commonName: "*.nilsherzig.com"
#   dnsNames:
#     - "*.nilsherzig.com"
