apiVersion: v1
kind: Pod
metadata:
  name: speedtest-pod
  namespace: default
  labels:
    name: speedtest-pod
spec:
  containers:
    - name: speedtest
      image: openspeedtest/latest
      ports:
        - containerPort: 3000
