{
 "title": "default",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "network down total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "network up total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "cpu usage total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (container) (100 * rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "network transmit by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace) (100 * rate(container_network_transmit_bytes_total{namespace!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (namespace) (-100 * rate(container_network_receive_bytes_total{namespace!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}