apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-tls
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: argo.nilsherzig.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-server
                port:
                  number: 80
  tls:
    - hosts:
        - argo.nilsherzig.com
      secretName: tls-argo-cert
