apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBo8hHx/KvShrAB9DpaZ7B4oDkhUdAYMuFd4rigXEcxesXw73EGOLpR8p0d1TOC4kYJVgGodtivRfuR8xRp4kYRybpW4VaaXkKVkp58On5tr8qODp6TTyTJlOh4MOmt3SUQdI+ATpixT7JH417XuLHue01yHpB1ZDvdN1R4LampAGnXUQHSm0U4V5Uq1B7BbeO3suQqZt0ePQ5lhIXjZfJ/yURaUsTj1wvpx1r48YST9mIXb2/eVsV4uCrlTJgwzndSOLbHoU/T4zbuI7SsTY+6UWGLjbkMRyTt8oXMbD2FQ6EfuMnFelchZkXvl4/A0cDMQ3r/6EGth2NfVqDBj1z7WBNTdBhMAnOJfEBwnBPxjqTOaOmXimqV6mfnVyrXKH7C764dEsV/VAyMiiTqcuLjXp2cyycMdX2x2QfXOrlJssBodlP+fAR8ufJBkooc7rk9VXf+MhTGsOh8mQXj4ULFY46EPvs767rO6f2NIJe+f2Z4kIxc2XWleh/QuGuaubj7ebm5gZQK5w7I4SROwFHEyNSQy5ZmPMz+4XIcUDFgYUVCzYfszQUzMTFYC4jOh7c4Vt/ET/S9F2jp1j9FzYXCG55UfU1ZeyaO+YW8VuWaWfT1UY4ffGHMuuC4PABltGssdGkpcRJ66Ujb/eHZHR5Vi7cg0vGRrS1ay4n/6J1Cp9EMiKbjHtB2XCW5AvKrY6NWDE+7D1XRF0sz5rJXLc6KV8mlETY2wlHoDvlupoe/Hl0jdLtJNR7N
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

