---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCS6eJHL0WMpt3R6d4ACs5a9CWOcYTQBca/SDZo9JjApxtEZJLa4gKo3rKkgXTIQyoVjQDIOleesCJesD2YS+fhGOhaAO1gY2gKDDlt4j8F1MWQRkCM53cStklV7LEdtxyLwsBi5IBicuivDO3GdyQYIXl3cijdzLhRTON7dTmnHBFvH8Hrc+f8xu0BqUJ1WZhehK6EHY2PW3CVbJcCKK03XB/sNw1RQONLZnCp3p9F6oCT4cECUWEE6rPSMTESEbNpBFntsgYPeJsSmyg02qDnZcL8GrlkNNmkXkuOsg50tXaypYnoM9N1RaLDgSBWEt6In1yyGSgk3zdXB5hr36O16jjhDK/17YNRBzGkGkuwDDtbSHFrSSKTcYjceIQccCdfwOJauU03RB3HQjPJzwnRZB81F0eYq7cqTFxes3DGyStUnyqy3I/Ixlrr+awZY8eUJmsf/5omZsmKgyp8U8xMowuk0dVlKOWV772AGsAyUdJHoxF5LESi+K7bxrISR/1eXvGpakFoPLk7ec9DX0jPUWYtzsiNt6ao7s5Fhiw9BZ7G/7ZcAQxWTlmPcJv5VsGyL3Upulcpusmhc0wMdovUc9c0UQhwrKiLXjpJwdb4FVH3tkltkp4J8RZxKU6N/baXp2Q9/VBuQ7flUVozcf56okCfB+lptMvz6p8gpUd10aZpDdXfH7n0mJdEsKJFyppVIpT0+t7FjXClzf/2D8/rab3whOBKprVHw+6iaZlD7YIyhSqGG0rp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
