---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC2Z693GudjeSJMm+fsi9GW/9sZSZD915eRW2B/PAqkdE3Hgb1s4nD4KMUtK43Ym5t4o/EWVER7kOgECcO5oeZIRIgLJh3JqGueOAb8ZkkWEFjLkjEE8NHZtslxkj8HqIt3BVEDl5d1TnAnoLrgBdsvH/D7+P/AK+l8HlII38M6etxaRVIBFKlP5Ue3lMWNVGDyT4sYEogplTLa0dLvEGwVXcCG8iEKDvzxokPFUcUfgy8EGYcfl7EDP2RsV7eFj+V+4QMQqOAhLB8ExrdICcq+u2+jAMujEyV/efON5J7zab81XC9GErlEjE3ItxzfXCBZEj3sdW6Xna5oIvMFbY1vCWDOE1ZlPFx9iqG7yEm02tkYwOiTHkZg1TaGOqukJAq5Fk367eT1zn7f0L+ZCpogwabOw3+Dv4OckD0f1QZUE6Lp5tLfTavm65ep1kaDub2DVv1r6b6iqg7bTRGv6Vv3Oq7SH7NscnEUmqTJF4YdPdj2JhctmI+87Ewnm7WkrUzCx9TMeLkoMbJNQ70MVpHI7sDBzLtnCgoP8oF8duAiZ9nZ0Ss3EwYithsnyS9arTYF4yqSVwhEnjnuUwjTFIJolGcsokXqtkR6CuWqKNj8zafDQzCh4MD1p6IVE6MpWSTHf18LgcnRY2f2Kbf5ygOu738MnP6+7GVaRMGAIa42S/x7sFKFfTLWKsQ+FBA1N4+ZlqQ4adeKaGJRRtMuMyYG18/UAWOj9ckFddVfN2CUx/hTxPUtqRFz
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
