---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAbC1YBpnxoI0Y2oO8CQ0YIL2ykJs/80vPNNTy9uTpkLWh5ccMotzIk50oZmSioEi0DuK2imOnnLi4fZAwgLwokpexaQsSJrJ4u+sBbjruFufqtfd6mbCevBPWBsQkohOFEZMjTEfN2NpO+Q6i1F1XKjpDxKFdjMtLsosqJ17WXJKAeP6kOwFyYzmIqbAzZlietK5R4/SSWpSXt66BkzaY/12i61/ejjJ3ZabLBplR2XjeM73RCNeBFHP5d40hr9e1OPiIz/WZ6r4nq62a7/D4g/5nEKHAbZ0qGasmw2K/c38WSWShxF3canlNwQMWmCeabKmVZ5J5HW4TJgYrlqz8wSKj/Oy7y1j20ofdYzgknhx3ZDO99uvVsW+TfUoPqafp17lTUOZfzhZEsoeXjEkEoe82R5PszbvMLug119A9iae5XeqWSwD2gDCtHw/wle0HkH/mR8nYGo3VruWku6wxeFcSbo68syLK0k4MNPCidtmNY7VvbrC1+9HqKZLhoCwhtE/S71nBNViJVM4wCWCeKuyrNhd7w8Ny3Wb8xu7VGwsPliK/lfO1jV4o9lBiusDhCytuGSEK5EQgL+3hAdlH9X95o/ljq9NMu6cv0huFiHImv26B2noopWB+3aAT3v4kfj0c+VXHElmOD2FOFqeiykfYqEnv1yS7raxvkMS3WszpavGx09y143GAdR+oWiqULGFIH7l03VF0pBHcd+0h0/sy//aF92MEpxHUjjTpKMO7/NPwf4lLx
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
