apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBdCSCZYOapcO8VNymKhT2uQcZ4KGJt2MU1XSXKMa+J+VLLWfUzLt5lj2yqi7Bx4yqGiTahLAs81pxZuiovDZ76nsgY2spKvs+CPfTbz70D136fnwekoheWW9sx93Jqr14EjzsOLZgd4a/QgPRCbS9bK+eWYJiXkwPR+uBZZT2E/gyFzgk5n4TJjDrdoFzm4NjDGMlu2/c9A4Ic5jgu9lRrBbBFHeIDkm2xxi8ip+CEkgYmeMAXRgDLDQ8Qu7m0ptaX81oq5azHzLjlwlAcrnbsdyxDCSPVor5Txxi6Tntu7+bYZV6SUN6jnQBb8kq8xGO5uHdZp7ASxFEzVn43ijQv+X/8je9s+7nRZEwAG8tF2b8lFHPZTu1zy7smrA9IWRBMNV8Wa90aF+/X1IEUgvWJSiG5gjRCnGcv7w3ijRFbTzDL0S/2vYkxaFuAJTlu1MvYhp0si7RGWPPkwZSuq6TM3HT5CkgG+okIoWFO2OFRdgkKrwgW1Yqqfz/GD1SVjIlY97JOG2bUAZC35m13c6xpD7UKDx2w+pyporknFxde3Ess5a9NVukWsBkO7yDEaZoJ3/WzQB7gbstqJRSp6538W217V0Jk93QRCKUaolL1i3swFyjkfavf+1YgrlsnCDTmqIXv21cskxWNLzu2LxjOPxKb8jMxStuwgCMZvdGoT8eltuU+9ZUm9uyetS4KfGM93zr0Qn3yhgn+1QFPFbnlvlvXL8FUwKWNiUimpladiJQjvZSgcwfQ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
---
