---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB/ZG1cATP4UAcKhKGItn97wgRTfwIoiAnd4bjR6G/Va6S5xhO2TiBJZsO1opsCmHp2IMOJMdHC3YnoZ/pzG4PZn31De4S4gNLygu/5+LzS953FHKgd0UO9KRcCXMT8eMXrwT1eTaE7ttlRKGIyFin5ZVovGhXrkXj+L8s9Pe5xoqj+QRjjcX4bUH7+d2GdccHyOX3/YtYJmCNIPSA3AE+vNZf6w4acE/+TJgh4O2KTHXcxIly2AiH/bipqVyCAHUhrEY2G52002zHJSscSyBEPfk+f9zSxkeBEoXlowS8TXdR68dskkj/hMeDHAVt9thVS4IKMkMkz8OULoVlfwRI3Cev4/XrNKr+uyRwvIt7xTKkBF2d4EusucspPP/dqZJGSTJ7P/ojShyQvp9r62xCLmY/58vvj1HWGhjFvCBH9JyingnUH8DeWg0X18NEShbbTo9Ey0J6c114UJpXqR4wfW76MN28pIDlj16FSKXvtvqFnD/oygvoikoUGwgcWJD1n8owBd2YzwZSQzJ2OoJHyZKxGE5wDplrhq1MAeYmaoRaQuERf7VaSjSleg1wNrsQKKCa8BorRTGUVBmhhcOeY7Fn/zr7NedX3LNHMFzoC3AU9I4lPZ6541YYQ46metwjvLrWT7TXFTK3uHeCaLFW6x8m+h+5ja8UgGj8zdQ7tJAa9WGw/rQygqTDBgRoIE57JLVwPYwZsfQ4gyv1bTFwpJoB2Xlrh1peAVZEs0JPGpFDyx8dCJdXD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
