---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: default
spec:
  encryptedData:
    api-token: AgBcsesNlA9pMAb6clxYgaSBT7XVXFGhzLlXoCZYVuEAbPfJdV0o+BKsAQ+a7mumoUbG3/RZDKD3DS4mkxgbD7FtshpA84m/oaRVSmMlNR1Q9Kx8Ub1vGj6XtwtwqzrkuoLAUI3tpUAHo5/nrY4x2cNOz9DSaVfBVuNUC9wPxaU7DZQ3e5WvDvCuuzR2g0vxXllKcoJy+zoW0GvpWeZOMmU+GcxHkT6D6Nm6jzYdg+MkpJ0yoxS0k4nVyhq3mCGBsPpyaj7g1Pm7L/olpi5lc8BPlNo36LSBrOiQ99P+N2f7lq9b8LYDo6/ZA1YZEzPO0AHTeld+pJ/wag+2mHgRY/NRo6FDRzt19UIowONmOCQCjJ3jYy/lneFfMsDUvurojq8L+Xuuacmi8ohXH9XcVk3I8o3g8AAs2njSpNO2cm9twdXukHklVmxsDEWa62+tFojZ7BgC2pSCVyBhU6Qse4uCOFAp5o9PI2tEgSkMhButk52f4TnwpWK85IkugQXpeTNG1ohDoN6bVJaI28yyefm6kcnXdMk9IjEQFOGLLFuZykSVlNHNEJ6tP4SZwXo7YMX0+GUCzcINfURoxQ1p8se6tk4moIOe1yedhMFvK1sJouwY8C7kAygBqWf1UfUGiXrlZs1n3i+b3ja4kLJHVZQR1NthGIYn6K1EzEP8qiKkHjt4bSKId2wcICpchcUTtVImMFUl3+YyqJBJe22Rw1gNEjudErcjKSaE8Dd1QFO1oeoqI9BHhNCp
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: default
