---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-dns-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBTNPfFuaR0cyqnUG6vRm7KtNsBW5eeNz8VXSSNrfBhvmN9Jud0LVwzpk4HH4x7Ij4RFPWTAQ2MTvJSfJq9IjexFTpR5qIk+Hbsp1ebYQWOnCFyB4vXbFDSIJLJ2Ops04iSZZ1DtbG6Zvbew90ZH6AQlLz0BVltO+yPWQEJLaOzzxKHPCqzao/FA6F5ZH24mjEuKyQleH2IV/Yy0S3uhtfCoZCXF4YydH4VVe8W5UKXQLqKNtUlYOkmyK7Lak0WJMUcFknqo4LZw1uGAsTfxSX7ieQfUqpasUAJ9WrsEfTQtefsBDCko1+H0/lN28ouTx219WWbyQvWsJr+/iloIpkgXq4dTYEsov5gMjZ0t+kZtjRdm0lEMxo6qxw+0lQ6oZXhVWFNYNOq6bY8+MNaw2ic5sttrIVOGW4w43f4ccugHKNfT+OA4BZpPJ3nPxpZeAtAWEMQC0m6m+doZTWTZ45qHcm48FGWHkWlZBPhoIK6PyhwHBBcCdvBaqbuTrvh2q7kcyXzjh9OI6hm0gqWPLsPBx9LJTfdG99d5LsaqOgTR/cs8LZFox2b0E71bzsJ1SNqIu82utxdAzjFHgc1T78rGL3HdjiC6eZ3UPc6zUHHqDW39Lo3wWVCdPSaaksR/247My6GqiZWHFGpfvKQrq2ufCt9/mexiOSMzmO2EoE4KExLnB3C2Z8aHquKWzRvEwb41cCl2bSvjie/eE/U5E53J006++e3DwFlMu3GJodEh5jselZmj/XJ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-dns-token
      namespace: cert-manager
