apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "ns-homepage"
spec:
  endpointSelector:
    matchLabels:
      namespace: homepage
  ingress:
    - fromEntities:
        - world
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "ns-media"
spec:
  endpointSelector:
    matchLabels:
      namespace: media
  ingress:
    - fromCIDRSet:
        - cidr: "10.10.10.0/24"
