apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-external-to-label-access-public"
spec:
  endpointSelector:
    matchLabels:
      namespace: homepage
  ingress:
    - fromEntities:
        - world
---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "allow-external-to-label-access-public"
spec:
  endpointSelector:
    matchLabels:
      namespace: media
  ingress:
    - fromEntities:
        - cluster
