apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv-3
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: truenas
    path: /mnt/bigdata/kubernetes/immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv-2
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nas
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: truenas
    path: /mnt/bigdata/kubernetes/immich
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: truenas
    path: /mnt/bigdata/kubernetes/immich
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: nas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-immich-redis-master-0
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nas
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-immich-postgresql-0
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nas
