apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-listener-homepage
      hostname: "nilsherzig.com"
      protocol: HTTPS
      port: 9090
      tls:
        mode: Terminate
        certificateRefs:
          - name: nilsherzig-com
      allowedRoutes:
        namespaces:
          from: All
    - name: https-listener-argocd # TODO use wildcards for *.dev.nilsherzig.com domains
      hostname: "*.dev.nilsherzig.com"
      protocol: HTTPS
      port: 8888
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-dev-nilsherzig-com
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
