apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: shared-gateway
  namespace: infra
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  listeners:
    - name: https-listener-wildcard-dev-nilsherzig-com # TODO *.dev.nilsherzig.com is only reachable from my local network
      hostname: "*.dev.nilsherzig.com"
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: wildcard-dev-nilsherzig-com
      allowedRoutes:
        namespaces:
          from: All

    - name: https-listener-nilsherzig-com
      hostname: "nilsherzig.com"
      protocol: HTTPS
      port: 9090
      tls:
        mode: Terminate
        certificateRefs:
          - name: nilsherzig-com
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: homepage
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
