apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "qbittorrent-outgoing"
spec:
  endpointSelector:
    matchLabels:
      app: qbittorrent
  egress:
    - toEntities:
        - world
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "qbittorrent-api-access"
spec:
  endpointSelector:
    matchLabels:
      app: qbittorrent
  egress:
    - toEntities:
        - world
  ingress:
    - formEndpoints:
        - matchLabels:
            - app: prowlarr
            - app: sonarr
            - app: radarr
    - toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
            # - port: "6881"
            #   protocol: ANY
