apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: qbittorrent
spec:
  endpointSelector:
    matchLabels:
      app: qbittorrent
  ingress:
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "8080"
    - fromCIDRSet:
        - cidr: 10.10.10.0/24
      toPorts:
        - ports:
            - port: "8080"
  egress:
    - toEntities:
        - world
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
