apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "sonarr"
spec:
  endpointSelector:
    matchLabels:
      app: sonarr
  egress:
    - toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "8989"
              protocol: TCP
