apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "sonarr"
spec:
  endpointSelector:
    matchLabels:
      app: sonarr
  egress:
    - toEntities:
        - cluster
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
  ingress:
    - fromEndpoints:
        - matchLabels:
            sonarr: "allow"
      toPorts:
        - ports:
            - port: "8989"
              protocol: TCP
