apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "prowlarr"
spec:
  endpointSelector:
    matchLabels:
      app: prowlarr
  egress:
    - toPorts:
        - ports:
            - port: "1080"
              protocol: ANY
            - port: "53"
              protocol: ANY
            - port: "8989"
              protocol: TCP
            - port: "7878"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "9696"
              protocol: TCP
