apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: prowlarr
spec:
  endpointSelector:
    matchLabels:
      app: prowlarr
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: sonarr
      toPorts:
        - ports:
            - port: "9696"
    - fromEndpoints:
        - matchLabels:
            app: radarr
      toPorts:
        - ports:
            - port: "9696"
    # - fromEntities:
    #     - world
    #   toPorts:
    #     - ports:
    #         - port: "8989"
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
        - matchLabels:
            app: sonarr
      toPorts:
        - ports:
            - port: "8989"
    - toEndpoints:
        - matchLabels:
            app: radarr
      toPorts:
        - ports:
            - port: "7878"
