apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
spec:
  selector:
    matchLabels:
      run: openspeedtest
  replicas: 2
  template:
    metadata:
      labels:
        run: openspeedtest
    spec:
      containers:
        - name: openspeedtest
          image: openspeedtest/latest
          ports:
            - containerPort: 3000
