apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: homepage
spec:
  endpointSelector:
    matchLabels:
      app: homepage
  ingress:
    - fromEntities:
        - cluster
    - fromCIDRSet:
        - cidr: 0.0.0.0/0
  egress:
    - {}
