apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mkdocs
spec:
  endpointSelector:
    matchLabels:
      app: mkdocs
  ingress:
    - fromEntities:
        - cluster
  egress:
    - {}
