apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mkdocs
spec:
  endpointSelector:
    matchLabels:
      app: mkdocs
  ingress:
    - fromCIDRSet:
        - cidr: 192.168.3.197/24
      toPorts:
        - ports:
            - port: "80"
    # - fromEntities:
    #     - cluster
  egress:
    - toCIDRSet:
        - cidr: 192.168.3.197/24
