apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mkdocs
spec:
  endpointSelector:
    matchLabels:
      app: mkdocs
  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "80"
    - fromCIDRSet:
        - cidr: 10.10.10.0/24
      toPorts:
        - ports:
            - port: "80"
  egress:
    - {}
