apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.13.0
    helm:
      releaseName: sealed-secrets
      parameters:
        - name: fullnameOverride
          value: sealed-secrets-controller
          forceString: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
