apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: work
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "git@github.com:nilsherzig/kubernetes-deployments.git"
    path: deployments/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: work 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
