apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lsm
  template:
    metadata:
      labels:
        app: lsm
    spec:
      containers:
        - name: backend
          image: nilsherzig/lsm:latest
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: lsm
spec:
  selector:
    app: lsm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
