apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cilium
      repoURL: https://helm.cilium.io/
      targetRevision: v1.16.0
      helm:
        valuesObject:
          k8sServiceHost: localhost
          k8sServicePort: 7445
          kubeProxyReplacement: true
          ipam:
            mode: kubernetes
          hubble:
            ui:
              enabled: true
            relay:
              enabled: true
          gatewayAPI:
            enabled: true
            hostNetwork:
              enabled: true
          cgroup:
            hostRoot: "/sys/fs/cgroup"
            autoMount:
              enabled: true
          bpf:
            hostLegacyRouting: false
          envoy:
            securityContext:
              capabilities:
                keepCapNetBindService: true
                envoy:
                  - NET_ADMIN
                  - NET_BIND_SERVICE
                  - SYS_ADMIN
          securityContext:
            capabilities:
              ciliumAgent:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
              cleanCiliumState:
                - NET_ADMIN
                - SYS_ADMIN
                - SYS_RESOURCE
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
