apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-staging
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: staging
  source:
    repoURL: https://github.com/nilsherzig/kubernetes-homelab.git
    targetRevision: HEAD
    path: ../overlays/staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
