apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: default
  source:
    chart: immich
    repoURL: https://immich-app.github.io/immich-charts
    targetRevision: 0.7.0
    helm:
      valuesObject:
        postgresql:
          enabled: true
        redis:
          enabled: true
        immich:
          persistence:
            library:
              existingClaim: immich-library-pvc

  destination:
    server: "https://kubernetes.default.svc"
    namespace: immich

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
