apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyfin"
spec:
  endpointSelector:
    matchLabels:
      app: jellyfin
  # egress:
  #   - toPorts:
  #       - ports:
  ingress:
    - toPorts:
        - ports:
            - port: "8096"
              protocol: TCP
