apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: jellyseerr
spec:
  endpointSelector:
    matchLabels:
      jellyseerr: ""
  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "5055"
  egress:
    - toFQDNs:
        - matchName: api.opensubtitles.com
      toPorts:
        - ports:
            - port: "443"
    - toEndpoints:
        - matchLabels:
            app: jellyfin
      toPorts:
        - ports:
            - port: "8906"
    - toEndpoints:
        - matchLabels:
            app: radarr
      toPorts:
        - ports:
            - port: "7878"
    - toEndpoints:
        - matchLabels:
            app: sonarr
      toPorts:
        - ports:
            - port: "8989"
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
