apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "jellyfin"
spec:
  endpointSelector:
    matchLabels:
      app: jellyfin
  egress:
    - toPorts:
        - ports:
            - port: "53"
              protocol: ANY
            - port: "443"
              protocol: TCP
  ingress:
    - toPorts:
        - ports:
            - port: "8096"
              protocol: TCP
