apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: stream.nilsherzig.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 80
  tls:
    - hosts:
        - stream.nilsherzig.com
      secretName: tls-jellyfin-cert
