apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling
  labels:
    app: stirling
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stirling
  template:
    metadata:
      labels:
        app: stirling
    spec:
      containers:
        - name: stirling
          image: frooodle/s-pdf:latest
          env:
            - name: LANGS
              value: "en_GB,de_DE"
            - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
              value: "false"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "3000Mi"
              cpu: "3000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          volumeMounts:
            - name: stirling
              mountPath: /configs
              subPath: extraConfigs
            - name: stirling
              mountPath: /usr/share/tessdata
              subPath: trainingData
      volumes:
        - name: stirling
          persistentVolumeClaim:
            claimName: stirling-data-many
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-data-many
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
