apiVersion: v1
kind: Pod
metadata:
  name: speedtest-pod
  labels:
    name: speedtest-pod
    testing: this is a change only applied to non prod clusters
spec:
  containers:
    - name: speedtest
      image: openspeedtest/latest
      ports:
        - containerPort: 3000
