apiVersion: v1
kind: Pod
metadata:
  name: speedtest-pod
  labels:
    name: speedtest-pod
    testing: a-change-on-the-dev-branch
spec:
  containers:
    - name: speedtest
      image: openspeedtest/latest
      ports:
        - containerPort: 3000
